### PR TITLE
Preamble moved inside of reactor to avoid multiple definitions

### PR DESCRIPTION
**Pull request by lhstrh**
`FurutaPendulum.lf` surprisingly wasn't compiling. We need to check our CI and find out why this wasn't flagged as such.

The problem is that even though building failed,`lfc` exited with `0`, which is why the error isn't being picked up by `action-check-lf-files`. This was because the build script was masking the failure. This script has been patched in this PR.

### CODE REVIEW

**Comment by axmmisaka** [comment]
I prefer wait until https://github.com/lf-lang/lingua-franca/pull/1988 is merged, then see if CI works as intended.

**Review by axmmisaka — APPROVED** [review]
I prefer wait until https://github.com/lf-lang/lingua-franca/pull/1988 is merged, then see if CI works as intended.

For `FurutaPendulum.lf` though, I don't know. If it works, it works.

**Comment by lhstrh** [comment]
It will break other things. But I agree, we can wait with this PR.

**Comment by cmnrd** [comment]
I am a bit confused by the title of this PR. The preamble is not private (as in using the private keyword), but nested within the reactor scope. This wording confuses me, because there is a clear meaning for private and public preamble in the C++ target. Are we overloading this terminology with a different meaning in the C target?

**Comment by lhstrh** [comment]
Things declared in a preamble of a reactor (as opposed to a file) do not leak into the scope of files that import them, hence the use of the term "private." Should I be calling it something else?

**Comment by cmnrd** [comment]
I am not sure. It seems that with recent changes in the C target the mechanisms for how preambles work in C and C++ have diverged significantly and now the terminology is ambiguous.

**Pull request merged**
