### PR TITLE
Fix examples for release 0.7.0

### LINKED ISSUE #103: CMake problem with MQTT examples
In the playground, compiling `examples/C/src/mqtt/MQTTDistributed.lf` now gives the following compile error, which did not occur before.  How to fix this?  Help please.  The error message means nothing to me.

```
CMake Error at paho-extension.cmake:49 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "federate__source".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * CMakeLists.txt:85 (target_link_libraries)
   * CMakeLists.txt:87 (target_link_libraries)
   * CMakeLists.txt:97 (target_link_libraries)
```

The offending line in `pho-extension.cmake` is this:

```
target_link_libraries(${LF_MAIN_TARGET} ${PAHO_MQTT_C_LIBRARIES})
```

### PR DESCRIPTION
**Pull request by cmnrd**
This PR updates the examples to be ready for the 0.7.0 release. This release introduces a couple of breaking changes and the examples need to be adjusted accordingly.

Fixes #103

### CODE REVIEW

**Comment by cmnrd** [comment]
@edwardalee I fixed the cmake issues, but now the linker complains in the ROS and MQTT examples. It is missing a reference to `SET_NEW_ARRAY'. Is this part of the old C API that got removed recently?

**Comment by edwardalee** [comment]
Just pushed updates to replace LF_SET_ARRAY.
I can't test the ROS code, and I'm not sure it's got the memory management quite right.
I've added a note to the code with a question of whether we should be calling `release_rcl_serialized_message`.

**Comment by cmnrd** [comment]
The memory management indeed looks suspicious. However, I don't understand the current implementation of tokens (and in particular its assumptions) well enough to comment on it.

Should we go ahead and merge this?

**Review by edwardalee — APPROVED** [review]
I think this is ready to merge.

**Comment by lhstrh** [comment]
> I think this is ready to merge.

It won't be ready to merge until we release `v0.7.0`...

**Comment by cmnrd** [comment]
We are in an inconsistent state anyway... Currently, the playground neither works with 0.6.0 nor with the current master. If we merge this, it will at least work with master.

**Pull request merged**
