### PR TITLE
Audio Classification example

### PR DESCRIPTION
**Pull request by vinzbarbuto**
Here are the files that demonstrate the Audio Classification example, complete with an installation and execution guide.

### CODE REVIEW

**Comment by lhstrh** [comment]
This looks really cool, but I want to caution against checking large binary files into git. A possible alternative would be to use https://git-lfs.com/.

**Comment by vinzbarbuto** [comment]
Indeed, the binary file comprises the Tensorflow Lite model. How would you recommend handling it?

**Comment by lhstrh** [comment]
> Indeed, the binary file comprises the Tensorflow Lite model. How would you recommend handling it?

I would suggest Git LFS.

**Comment by lhstrh** [comment]
Thanks for trying out LFS! Note that 6d34a5719115b55ba73ae93a4a39e9b726a7347e has deposited the file into the history already, so that commit would have to be rewritten before this PR gets merged.

**Review by lhstrh — APPROVED** [review]
Thanks for cleaning up the history and using LFS!

**Pull request merged**
